trigger:
  branches:
    include:
      - master

variables:
  imageName: 'devsu-node-app'
  dockerRegistryServiceConnection: 'DOCKER_HUB_CONN'
  dockerRepository: 'diegosva182/devsu-node-app'

pool:
  vmImage: 'ubuntu-latest'

stages:

# ----------------------
# STAGE: Build & Test
# ----------------------
- stage: Build
  displayName: 'Build & Test Node App'
  jobs:
    - job: Build
      displayName: 'Install, Test, Lint'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run test -- --coverage
            if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
              npx eslint .
            fi
          displayName: 'Run Tests and Lint'

# ----------------------
# STAGE: Docker Build & Push
# ----------------------
- stage: Docker
  displayName: 'Docker Build and Push'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: Docker
      displayName: 'Build & Push Docker Image'
      steps:
        - task: Docker@2
          displayName: 'Docker Build & Push'
          inputs:
            containerRegistry: '$(dockerRegistryServiceConnection)'
            repository: '$(dockerRepository)'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              latest
# Optional kubernetes deployment to azure
        # - task: KubernetesManifest@1
        #   inputs:
        #     action: deploy
        #     kubernetesServiceConnection: 'conexion'
        #     namespace: 'default'
        #     manifests: |
        #       k8s/deployment.yaml
        #       k8s/service.yaml
        #       k8s/hpa.yaml
        #     containers: |
        #       diegosva/devsu-node-app:latest
