apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-node-app
  template:
    metadata:
      labels:
        app: devsu-node-app
    spec:
      containers:
        - name: app
          image: diegosva182/devsu-node-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
